# -*- coding: utf-8 -*-
"""Sentiment_and_anomaly/12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VQJGOopyLAfUNjM9lZ0DgYXBkp1B7dKa
"""

from getpass import getpass
import os

# Set up GitHub username and personal access token (PAT)
username = "Sahilgulati2006"
token = "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"

# Set GitHub credentials for authentication
os.system(f'git config --global user.email "sahilgulati.in@gmail.com"')
os.system(f'git config --global user.name "{username}"')
os.system(f'git clone https://{username}:{token}@github.com/Sahilgulati2006/Stock-testing.git')

!pip install numpy pandas matplotlib seaborn yfinance tweepy transformers datasets scikit-learn torch

!pip install polygon-api-client

from polygon import RESTClient


API_KEY = "hxGeYKs1qclcdpNgPzniVjNvtgIcbulg"
client = RESTClient(API_KEY)

!pip install praw

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
import praw
import tweepy
from transformers import pipeline
from sklearn.ensemble import IsolationForest

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/nasdaq-listed.csv')
print(df.head())

tickers_nasdaq = df['Symbol'].tolist()
print(tickers_nasdaq[0:10])

from datetime import date
import praw
import re
from collections import Counter

# Reddit API Setup
reddit = praw.Reddit(
    client_id="_f9G2wmqD_D-8BU7usAkuw",
    client_secret="gLt3IkPt4B-GrPV-yQ44-LUy2XXmnQ",
    user_agent="sahilprostar/1.0"
)

# Load NASDAQ tickers (assuming tickers_nasdaq is already loaded from CSV)
Subreddit = input("Enter the subreddit name (default: WallStreetBets): ") or "wallstreetbets"
subreddit_chosen = reddit.subreddit(Subreddit)
hot_posts = subreddit_chosen.hot(limit=50)

# Extract NASDAQ tickers from Reddit (Titles, Bodies, and Comments)
tickers_reddit = []

for post in hot_posts:
    # Extract tickers from post title
    words_title = re.findall(r'\b[A-Z]{2,5}\b', post.title)
    valid_tickers_title = [word for word in words_title if word in tickers_nasdaq]
    tickers_reddit.extend(valid_tickers_title)

    # Extract tickers from post body (selftext)
    if post.selftext:
        words_body = re.findall(r'\b[A-Z]{2,5}\b', post.selftext)
        valid_tickers_body = [word for word in words_body if word in tickers_nasdaq]
        tickers_reddit.extend(valid_tickers_body)

    # Extract tickers from comments
    post.comments.replace_more(limit=0)  # Load all comments
    for comment in post.comments.list():
        if comment.body:
            words_comment = re.findall(r'\b[A-Z]{2,5}\b', comment.body)
            valid_tickers_comment = [word for word in words_comment if word in tickers_nasdaq]
            tickers_reddit.extend(valid_tickers_comment)

# Count top mentioned stocks
top_stocks = Counter(tickers_reddit).most_common(10)

# Display results
print("\n📅 Date:", date.today())
print("📈📉 Top 10 Mentioned Stocks on Reddit (Titles, Bodies & Comments):")
for idx, (stock, count) in enumerate(top_stocks, 1):
    print(f"{idx}. {stock} ({count} mentions)")

selected_stock = input("Enter a stock ticker to analyze: ").upper()
if selected_stock in tickers_nasdaq:

    # Fetch latest news
    news = client.list_ticker_news(selected_stock, limit=3)
    for item in news:
      print(f"📰 {item.published_utc} | {item.title}\n{item.description}\n")

else:
    print("⚠️ Invalid ticker symbol.")

F_report = input("Do you want a basic fundamental report (Y/N): ").upper()
if F_report == "Y":
  fundamentals = client.get_ticker_details(selected_stock)
  print("🔍 Fundamental Analysis:")
  print(f"📌 Name: {fundamentals.name}")
  print(f"🏢 Industry: {fundamentals.sic_description}")
  print(f"💰 Market Cap: ${fundamentals.market_cap}")

